INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Contact','-1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Cotact Us','-1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('About','-1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('About Us','-1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Register','-1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Sign In','-1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Sign-In','-1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Place an Ad','-1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('twitter','-1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Sign Up','-1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Sign-Up','-1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Jobs','-1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Terms of Service','-1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Privacy Policy','-1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Advertise','-1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Staff Bios','-1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Subscribe','-1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('A&E','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Adventure','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Arts','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Arts & Culture','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Arts & Entertainment','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Arts And Culture','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Arts And Entertainment','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('At Home','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Auto','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Auto','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Auto Reviews','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Best of','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Biology','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Blog','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Blogs','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Books','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Business','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Business Schools','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Calendar','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Capital','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Chemistry','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('City & Region','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('City And Region','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Columnists','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Comedy','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Commentary','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Communities','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Community','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Community Calendar','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Companies & Industries','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Companies and Industries','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Contests','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Contests/Promotions','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Country Morning','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Culture','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Culture','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Deaths','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Design','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Earth','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('EatPlayLive','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Eats','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Education','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Elections','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Energy/Environment','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Entertainment','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Entertainment/Life','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Events','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Family Matters','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Fashion','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Fashion & Style','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Fashion And Style','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Features','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Film','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Food & Drink','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Food & Fun','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Food And Drink','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Food And Fun','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Food+Drink','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Future','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Global Economics','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Gusto','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Health','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Healthwise','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Healthy Living','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Home','3');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Innovation','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Innovation & Design','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Innovation And Design','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Investigations','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Investigative','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Issues','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Justice','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Life','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Life & Arts','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Life & Culture','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Life And Arts','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Lifestyle','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Lifestyles','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Living','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Local','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Local News','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Market Data','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Marketplace','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Markets','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Markets & Finance','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Markets And Finance','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Media','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Money','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Morning','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Movies','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('MultiMedia','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Music','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Nation Now','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Neighborhoods','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('News','3');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('News Headlines','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('News+Features','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Obits','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Obituaries','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('On-Air','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Opinion','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Opinions','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Our Towns','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Outdoors','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Perspectives','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Photo','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Photos','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Photos/Video','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Physics','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Places','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Politics','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Politics & Policy','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Politics and Policy','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Promotions','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Real Estate','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Religion','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Restaurants','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Scene','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Science','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Screen','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Society','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Space','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Special Reports','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Sports','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Stage','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('State','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Style','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Sunrise','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('T.V.','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Tech','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Tech/Biz','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Technology','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Things To Do','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Today','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Traffic','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Travel','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Trends','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('TV','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('TV & Video','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('TV And Video','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('U.S.','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('U.S./World','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('U.S.A','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('USA','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Video','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Video & Multimedia','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Video and Multimedia','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Video/Pics','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Views','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Voices','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Weather','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Weekend','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Weird','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('World','1');
INSERT INTO `menuLabelWeights`(`MLW_name`, `MLW_weight`) VALUES ('Worldpost','1')
